{{ config(
    materialized='table',
    persist_docs={'relation': True, 'columns': True},
    post_hook=['ANALYZE TABLE {{ this }} COMPUTE STATISTICS'],
    description='This model creates a denormalized Customer 360 flat table by joining CRM, Billing, Marketing, Support, and Service data. The table is built at a daily frequency using the unique CRM_CUSTOMERS.CUSTOMER_ID as the grain'
) }}

with 

CRM_CUSTOMERS as (
    select * from {{ source('db_source', 'CRM_CUSTOMERS') }}
),

BIL_INVOICES as (
    select * from {{ source('db_source', 'BIL_INVOICES') }}
),

BIL_INVOICE_ITEMS as (
    select * from {{ source('db_source', 'BIL_INVOICE_ITEMS') }}
),

BIL_PAYMENTS as (
    select * from {{ source('db_source', 'BIL_PAYMENTS') }}
),

CRM_ACCOUNTS as (
    select * from {{ source('db_source', 'CRM_ACCOUNTS') }}
),

CRM_CONTACTS as (
    select * from {{ source('db_source', 'CRM_CONTACTS') }}
),

CRM_OPPORTUNITIES as (
    select * from {{ source('db_source', 'CRM_OPPORTUNITIES') }}
),

MKT_CAMPAIGN_TARGETS as (
    select * from {{ source('db_source', 'MKT_CAMPAIGN_TARGETS') }}
),

MKT_CAMPAIGNS as (
    select * from {{ source('db_source', 'MKT_CAMPAIGNS') }}
),

SUP_TICKETS as (
    select * from {{ source('db_source', 'SUP_TICKETS') }}
),

SUP_TICKET_NOTES as (
    select * from {{ source('db_source', 'SUP_TICKET_NOTES') }}
),

PRV_SERVICE_ASSIGNMENTS as (
    select * from {{ source('db_source', 'PRV_SERVICE_ASSIGNMENTS') }}
),

PRV_SERVICES as (
    select * from {{ source('db_source', 'PRV_SERVICES') }}
)

select
    CRM_CUSTOMERS.CUSTOMER_ID,
    CRM_CUSTOMERS.FIRST_NAME,
    CRM_CUSTOMERS.MIDDLE_NAME,
    CRM_CUSTOMERS.LAST_NAME,
    CRM_CUSTOMERS.EMAIL,
    CRM_CUSTOMERS.PHONE,
    CRM_CUSTOMERS.DATE_OF_BIRTH,
    CRM_CUSTOMERS.ADDRESS_LINE1,
    CRM_CUSTOMERS.ADDRESS_LINE2,
    CRM_CUSTOMERS.CITY,
    CRM_CUSTOMERS.STATE,
    CRM_CUSTOMERS.ZIP_CODE,
    CRM_CUSTOMERS.COUNTRY,
    CRM_CUSTOMERS.CUSTOMER_SEGMENT,
    CRM_CUSTOMERS.CUSTOMER_TIER,
    CRM_CUSTOMERS.START_DATE,
    CRM_CUSTOMERS.STATUS,
    CRM_CUSTOMERS.NOTE,
    CRM_CUSTOMERS.CREATED_AT as Customer_Created_At,
    CRM_CUSTOMERS.UPDATED_AT as Customer_Updated_At,

    CRM_ACCOUNTS.ACCOUNT_ID,
    CRM_ACCOUNTS.ACCOUNT_TYPE,
    CRM_ACCOUNTS.CREATION_DATE as Account_Creation_Date,
    CRM_ACCOUNTS.STATUS as Account_Status,
    CRM_ACCOUNTS.CURRENCY_CODE as Account_Currency,
    CRM_ACCOUNTS.BILLING_ADDRESS,
    CRM_ACCOUNTS.SHIPPING_ADDRESS,
    CRM_ACCOUNTS.ACCOUNT_BALANCE,

    CRM_CONTACTS.CONTACT_ID,
    CRM_CONTACTS.CONTACT_TYPE,
    CRM_CONTACTS.CONTACT_VALUE,
    CRM_CONTACTS.IS_PRIMARY,
    CRM_CONTACTS.CONTACT_LABEL,

    BIL_INVOICES.INVOICE_ID,
    BIL_INVOICES.INVOICE_DATE,
    BIL_INVOICES.DUE_DATE,
    BIL_INVOICES.TOTAL_AMOUNT,
    BIL_INVOICES.TAX_AMOUNT,
    BIL_INVOICES.DISCOUNT_AMOUNT,
    BIL_INVOICES.CURRENCY_CODE as Invoice_Currency,
    BIL_INVOICES.STATUS as Invoice_Status,
    BIL_INVOICES.NOTE as Invoice_Note,
    BIL_INVOICES.CREATED_AT as Invoice_Created_At,
    BIL_INVOICES.UPDATED_AT as Invoice_Updated_At,

    BIL_INVOICE_ITEMS.ITEM_CODE,
    BIL_INVOICE_ITEMS.DESCRIPTION as Item_Description,
    BIL_INVOICE_ITEMS.QUANTITY,
    BIL_INVOICE_ITEMS.UNIT_PRICE,
    BIL_INVOICE_ITEMS.TAX_RATE,
    BIL_INVOICE_ITEMS.DISCOUNT_RATE,
    BIL_INVOICE_ITEMS.LINE_TOTAL,
    BIL_INVOICE_ITEMS.CREATED_AT as Item_Created_At,
    BIL_INVOICE_ITEMS.UPDATED_AT as Item_Updated_At,

    BIL_PAYMENTS.PAYMENT_ID,
    BIL_PAYMENTS.PAYMENT_DATE,
    BIL_PAYMENTS.AMOUNT as Payment_Amount,
    BIL_PAYMENTS.PAYMENT_METHOD,
    BIL_PAYMENTS.TRANSACTION_ID,
    BIL_PAYMENTS.CURRENCY_CODE as Payment_Currency,
    BIL_PAYMENTS.NOTE as Payment_Note,
    BIL_PAYMENTS.CREATED_AT as Payment_Created_At,
    BIL_PAYMENTS.UPDATED_AT as Payment_Updated_At,

    CRM_OPPORTUNITIES.OPPORTUNITY_ID,
    CRM_OPPORTUNITIES.STAGE,
    CRM_OPPORTUNITIES.PIPELINE_STAGE,
    CRM_OPPORTUNITIES.AMOUNT as Opportunity_Amount,
    CRM_OPPORTUNITIES.PROBABILITY_OF_CLOSE,
    CRM_OPPORTUNITIES.CLOSE_DATE,
    CRM_OPPORTUNITIES.ASSIGNED_SALES_REP,
    CRM_OPPORTUNITIES.NEXT_STEP,
    CRM_OPPORTUNITIES.NOTE as Opportunity_Note,
    CRM_OPPORTUNITIES.CREATED_AT as Opportunity_Created_At,
    CRM_OPPORTUNITIES.UPDATED_AT as Opportunity_Updated_At,

    MKT_CAMPAIGN_TARGETS.TARGET_ID,
    MKT_CAMPAIGN_TARGETS.CAMPAIGN_ID,
    MKT_CAMPAIGN_TARGETS.ASSIGNED_DATE,
    MKT_CAMPAIGN_TARGETS.STATUS as Campaign_Target_Status,
    MKT_CAMPAIGN_TARGETS.LAST_CONTACT_DATE,
    MKT_CAMPAIGN_TARGETS.CHANNEL,
    MKT_CAMPAIGN_TARGETS.RESPONSE_FLAG,
    MKT_CAMPAIGN_TARGETS.CREATED_AT as Campaign_Target_Created_At,
    MKT_CAMPAIGN_TARGETS.UPDATED_AT as Campaign_Target_Updated_At,

    SUP_TICKETS.TICKET_ID,
    SUP_TICKETS.CREATED_DATE as Ticket_Created_Date,
    SUP_TICKETS.STATUS as Ticket_Status,
    SUP_TICKETS.PRIORITY,
    SUP_TICKETS.SUBJECT,
    SUP_TICKETS.DESCRIPTION as Ticket_Description,
    SUP_TICKETS.CHANNEL_OF_CONTACT,
    SUP_TICKETS.ASSIGNED_AGENT,
    SUP_TICKETS.RESOLUTION_DATE,
    SUP_TICKETS.CREATED_AT as Ticket_Created_At,
    SUP_TICKETS.UPDATED_AT as Ticket_Updated_At,

    SUP_TICKET_NOTES.NOTE_ID,
    SUP_TICKET_NOTES.NOTE_DATE,
    SUP_TICKET_NOTES.NOTE_AUTHOR,
    SUP_TICKET_NOTES.NOTE_TEXT,
    SUP_TICKET_NOTES.INTERNAL_FLAG,
    SUP_TICKET_NOTES.CREATED_AT as Ticket_Note_Created_At,
    SUP_TICKET_NOTES.UPDATED_AT as Ticket_Note_Updated_At,

    PRV_SERVICE_ASSIGNMENTS.ASSIGNMENT_ID,
    PRV_SERVICE_ASSIGNMENTS.START_DATE as Service_Start_Date,
    PRV_SERVICE_ASSIGNMENTS.END_DATE as Service_End_Date,
    PRV_SERVICE_ASSIGNMENTS.STATUS as Service_Assignment_Status,
    PRV_SERVICE_ASSIGNMENTS.PROVISIONING_STATUS,
    PRV_SERVICE_ASSIGNMENTS.LAST_MODIFIED_DATE,
    PRV_SERVICE_ASSIGNMENTS.NOTE as Service_Assignment_Note,
    PRV_SERVICE_ASSIGNMENTS.CREATED_AT as Service_Assignment_Created_At,
    PRV_SERVICE_ASSIGNMENTS.UPDATED_AT as Service_Assignment_Updated_At,

    PRV_SERVICES.SERVICE_ID,
    PRV_SERVICES.SERVICE_NAME,
    PRV_SERVICES.SERVICE_TYPE,
    PRV_SERVICES.DESCRIPTION as Service_Description,
    PRV_SERVICES.MONTHLY_COST,
    PRV_SERVICES.ACTIVE_FLAG,
    PRV_SERVICES.PROVISIONING_TEAM,
    PRV_SERVICES.CREATED_DATE as Service_Created_Date,
    PRV_SERVICES.UPDATED_AT as Service_Updated_At,

    -- Aggregated Metrics
    (select count(*) from BIL_INVOICES where CUSTOMER_ID = CRM_CUSTOMERS.CUSTOMER_ID) as total_invoices_count,
    (select sum(TOTAL_AMOUNT) from BIL_INVOICES where CUSTOMER_ID = CRM_CUSTOMERS.CUSTOMER_ID) as total_invoiced_amount,
    (select sum(PAYMENT_AMOUNT) from BIL_PAYMENTS 
        join BIL_INVOICES on BIL_INVOICES.INVOICE_ID = BIL_PAYMENTS.INVOICE_ID 
        where BIL_INVOICES.CUSTOMER_ID = CRM_CUSTOMERS.CUSTOMER_ID) as total_payments_received,
    (select avg(TOTAL_AMOUNT) from BIL_INVOICES where CUSTOMER_ID = CRM_CUSTOMERS.CUSTOMER_ID) as average_invoice_amount,
    (select count(*) from CRM_OPPORTUNITIES 
        where ACCOUNT_ID in (select ACCOUNT_ID from CRM_ACCOUNTS where CUSTOMER_ID = CRM_CUSTOMERS.CUSTOMER_ID)) as total_opportunities,
    (select count(*) from PRV_SERVICES 
        where SERVICE_ID in (select SERVICE_ID from PRV_SERVICE_ASSIGNMENTS where CUSTOMER_ID = CRM_CUSTOMERS.CUSTOMER_ID)) as total_services

from CRM_CUSTOMERS
    left join BIL_INVOICES on CRM_CUSTOMERS.CUSTOMER_ID = BIL_INVOICES.CUSTOMER_ID
    left join BIL_INVOICE_ITEMS on BIL_INVOICES.INVOICE_ID = BIL_INVOICE_ITEMS.INVOICE_ID
    left join BIL_PAYMENTS on BIL_INVOICES.INVOICE_ID = BIL_PAYMENTS.INVOICE_ID
    left join CRM_ACCOUNTS on CRM_CUSTOMERS.CUSTOMER_ID = CRM_ACCOUNTS.CUSTOMER_ID
    left join CRM_CONTACTS on CRM_CUSTOMERS.CUSTOMER_ID = CRM_CONTACTS.CUSTOMER_ID
    left join CRM_OPPORTUNITIES on CRM_ACCOUNTS.ACCOUNT_ID = CRM_OPPORTUNITIES.ACCOUNT_ID
    left join MKT_CAMPAIGN_TARGETS on CRM_CUSTOMERS.CUSTOMER_ID = MKT_CAMPAIGN_TARGETS.CUSTOMER_ID
    left join MKT_CAMPAIGNS on MKT_CAMPAIGN_TARGETS.CAMPAIGN_ID = MKT_CAMPAIGNS.CAMPAIGN_ID
    left join SUP_TICKETS on CRM_CUSTOMERS.CUSTOMER_ID = SUP_TICKETS.CUSTOMER_ID
    left join SUP_TICKET_NOTES on SUP_TICKETS.TICKET_ID = SUP_TICKET_NOTES.TICKET_ID
    left join PRV_SERVICE_ASSIGNMENTS on CRM_CUSTOMERS.CUSTOMER_ID = PRV_SERVICE_ASSIGNMENTS.CUSTOMER_ID
    left join PRV_SERVICES on PRV_SERVICE_ASSIGNMENTS.SERVICE_ID = PRV_SERVICES.SERVICE_ID;